### ISSUE TITLE
metamath.exe file for Windows

### ISSUE THREAD

**Issue by FrankHubeny** [metamath/metamath-exe#172]
I couldn't find the metamath.exe file for Windows.

**Comment by benjub** [comment]
You can download it from https://us.metamath.org/index.html#downloads but his may not be the latest version.

**Comment by digama0** [comment]
It is the latest version, there is a fresh build of master every day.

**Comment by FrankHubeny** [comment]
Thank you! I downloaded it.

Frank Hubeny

Sent with [Proton Mail](https://proton.me/) secure email.
