### ISSUE TITLE
Arrow keys do not work on linux

### ISSUE THREAD

**Issue by icecream17** [metamath/metamath-exe#176]
On windows, I can press <kbd>Up</kbd> to go back to the previous command, <kbd>Dn</kbd> to go forward in the command history, and <kbd>Lt</kbd> and <kbd>Rt</kbd> to move the cursor left and right in commands.

But on linux (or at least, WSL2(bash) and cloud), pressing the arrows keys generates `^[[A` `^[[B` `^[[C` and `^[[D` combinations. 

Presumably it's something to do with https://stackoverflow.com/questions/21384040/why-does-the-terminal-show-a-b-c-d-when-pressing-the-arrow-k

**Comment by Taneb** [comment]
From the README:

> Optional rlwrap user interface enhancement
> ------------------------------------------
> 
> On Linux/MacOSX/Unix, the Metamath program will be more pleasant to use if you
> run it inside of rlwrap:
> 
>   http://utopia.knoware.nl/~hlub/uck/rlwrap/ (checked 15-Feb-2014)
> 
> which provides up-arrow command history and other command-line editing
> features.  After you install rlwrap per its instructions, invoke the Metamath
> program with "rlwrap ./metamath set.mm".
> 
> The Windows version of the Metamath program was compiled with lcc, which has
> similar features built-in.)

**Comment by icecream17** [comment]
I don't know how I missed that, thanks!
