### ISSUE TITLE
Change two options to "verify markup"

### ISSUE THREAD

**Issue by benjub** [metamath/metamath-exe#28]
In [PR #2392](https://github.com/metamath/set.mm/pull/2392), the date at the top of set.mm and iset.mm was removed. Therefore, the "verify markup" command that is run by the CI was changed to add the option "skip_top_date" (this was already *meant* to be the case, but it was not: this was fixed in that PR, see the changes in "scripts/verify").

Considering this, it seems natural that the default behavior of "verify markup" should be the one currently obtained with the two options "/top_date_skip /file_skip". These options should should be kept for backward compatibility (although they would have no effect). Additionally, the two options /top_date_chek and /file_check should be added, to restore the current default behavior if needed.

**Edit:** Maybe do this only for /top_date_skip and /top_date_check. The CI still runs the file check (it is only locally that the user generally types /file_skip).

**Comment by jkingdon** [comment]
> Additionally, the two options /top_date_chek and /file_check should be added, to restore the current default behavior if needed.

Do we need this part? I mean, if someone wants a top date they can still have it (minus this check), but isn't it simpler to get metamath.exe out of the top date checking business?

> Maybe do this only for /top_date_skip

Agreed. /file_skip is a separate issue and I'm not as convinced that we want to change anything with that one.

**Comment by benjub** [comment]
You're right, we don't really need a /top_date_check that restores the current default behavior, but the code for that behavior is already written, so adding the option is not a big work. Plus, there was some note in a recent discussion about not deprecating apparently useless features.

**Comment by wlammen** [comment]
I wonder whether the change *SKIP -> *CHECK should be noted in the changelog.  This is a user visible change.

**Comment by digama0** [comment]
Oops, forgot about that. Added this in 87c4352
