### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by wlammen** [metamath/metamath-exe#33]
We need to improve on documentation.  And how it is done.

Visit https://github.com/metamath/metamath-exe/pull/32 and explore a possible solution.  Discussion started there, but IMHO it should be continued here.  Let me know what you think.

**Comment by wlammen** [comment]
Are there any objections to follow these rules for documentation?
https://github.github.com/gfm/#introduction

I would like to come to a decision soon.

**Comment by digama0** [comment]
That's a markdown spec, not documentation rules, but if I understand you correctly then please go ahead. Even in the worst case, if we want to change documentation format later we can do so without too much work. Writing the content is the hard part.

**Comment by wlammen** [comment]
I deliberately chose a markdown spec to speed up the decision.

**Comment by wlammen** [comment]
Based on this discussion I added a pull request adding a doc folder with a draft of simple documentation rules.  Please review.
