### ISSUE TITLE
adding a /SKIPLONGPROOF parameter to the MINIMIZE_WITH command

### ISSUE THREAD

**Issue by glacode** [metamath/metamath-exe#95]
If I'm not mistaken, the statement to be minimized is

g_proveStatement

and here

https://github.com/metamath/metamath-exe/blob/adb9bec92afeb0dbc65fee0aa7c029bcf8c4fb8f/src/metamath.c#L5145

origCompressedLength is computed (see the statement following the one linked above)

Thus, it looks like a

if ( origCompressedLength > THRESHOLD )
may do the job. If that's the case, the "difficult" part should just be to add / store the new parameter(s).

As a final note, it looks like the MINIMIZE_WITH segment of code is all contained in the if statement that starts here

https://github.com/metamath/metamath-exe/blob/adb9bec92afeb0dbc65fee0aa7c029bcf8c4fb8f/src/metamath.c#L5051

BR
Glauco

**Comment by glacode** [comment]
This has been discussed here

https://github.com/metamath/set.mm/pull/2708#issue-1315871002

**Comment by savask** [comment]
What is the desired behavior? As far as I understand, `minimize */allow */no_new ax-* /skiplongproof` is supposed to do nothing, but notice that even the `prove theoremname` command may take a long time for theorems like fourierdlem102.

Unless I misunderstood the idea, I think this functionality can be implemented in a shell script (we use scripts for bulk minimization anyway), for example, the scheduling script we used for the global minimize run used theorem sizes to plan jobs evenly.

As an alternative, one could add a /skiplongproof option or its alternative to the `show proof *` command.

**Comment by glacode** [comment]
Hi savask,

  the desired behavior is to skip the minimize process and (maybe) write to the log something like
  "Theorem xxx was not minimized because its proof is nnnn steps, and it exceeds the given threshold of mmmm steps"
  
  Please, notice that I don't use the minimize command that often (I use it only for the theorems of my current PR) but as you can read here 
  
  https://github.com/metamath/set.mm/pull/2708#issue-1315871002
  
  those who perform periodic bulk optimizations, get stuck when a theorem with a long proof is included in the list of theorems to be minimized.
  
  Of course, the script could be set up to avoid those long theorems upfront, but this would require a "smart" script builder. Instead, most of the times, the scripts are created selecting a list of theorems "from number j to number k", or using wildcards for the names and so on.

BR
Glauco

**Comment by savask** [comment]
I tested potential time savings from this suggestion. The following command
```
prove fourierdlem103
```
takes 6m44s on my computer, while
```
prove fourierdlem103
minimize_with fvoveq1
```
takes 43m38s. 

I must admit that I underestimated the amount of time `minimize_with` takes even after `prove` did process the proof in full (waiting 6 minutes just to do nothing is still a long time, in my opinion).

**Comment by benjub** [comment]
@savask : you're right, it would be best to even avoid "prove xxx" if xxx has a long proof. To do this at script level, it would be sufficient to have a command `MM> SHOW LONGPROOFS nnn` which would output the labels of all $p-statements with proofs at least `nnn` bytes in compressed format. Then, with scripts, one could remove the output list from the other label list. (Alternately, have a command `SHOW SHORTPROOFS` and take an intersection of the lists. I don't know what would be best.)

**Comment by savask** [comment]
I think the best way would be to use the already existing `show proof * /size` command.

**Comment by benjub** [comment]
@savask: I'm not sure which you propose:
* add a MM command `show longproofs` which uses the existing function `show proof * /size`
* leave metamath.c unchanged and do everything in scripts using `show proof * /size` ?

(I'm not sure how easy it is to do the latter in a script.)

**Comment by savask** [comment]
Yes, I suggest to leave metamath.c unchanged and do everything in scripts. It shouldn't be very hard, for example, take a look at the scheduling script used for the previous minimization run: https://gist.github.com/savask/e44ee6086a1321b2bbddbce027975bae#file-preparejobs-sh-L40-L44

**Comment by benjub** [comment]
Thanks. So I guess this issue can be closed ?

**Comment by glacode** [comment]
I've reported the suggested solution here

https://github.com/metamath/set.mm/pull/2708#issue-1315871002

**Comment by jkingdon** [comment]
Based on the discussion above looks like this issue can be closed, and I'm doing so. Feel free to re-open (or perhaps better, create a new issue with the parts which are still live issues) if there is anything remaining to be done on this.
